### ISSUE TITLE
No devices loaded

### ISSUE THREAD

**Issue by danhajduk** [dcmeglio/homeassistant-petsafe#21]
i do not have any devices loaded. I get this error when trying to reconfigure it:
```
Logger: homeassistant.components.select
Source: helpers/entity_platform.py:366
integration: Select (documentation, issues)
First occurred: 5:39:22 PM (2 occurrences)
Last logged: 6:38:41 PM

Error while setting up petsafe platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/petsafe/select.py", line 24, in async_setup_entry
    SelectEntities.PetSafeLitterboxSelectEntity(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass=hass,
        ^^^^^^^^^^
    ...<5 lines>...
        entity_category=EntityCategory.CONFIG,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/petsafe/SelectEntities.py", line 73, in __init__
    sw_version=device.firmware,
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/petsafe/devices.py", line 454, in firmware
    return self.data["shadow"]["state"]["reported"]["firmware"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'firmware'
``` 

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366
integration: Sensor (documentation, issues)
First occurred: 5:39:22 PM (2 occurrences)
Last logged: 6:38:41 PM

Error while setting up petsafe platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/petsafe/sensor.py", line 69, in async_setup_entry
    SensorEntities.PetSafeLitterboxSensorEntity(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass=hass,
        ^^^^^^^^^^
    ...<4 lines>...
        icon="mdi:rake",
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/petsafe/SensorEntities.py", line 86, in __init__
    sw_version=device.firmware,
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/petsafe/devices.py", line 454, in firmware
    return self.data["shadow"]["state"]["reported"]["firmware"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'firmware'
``` 

``` 
Logger: homeassistant.components.button
Source: helpers/entity_platform.py:366
integration: Button (documentation, issues)
First occurred: 5:39:22 PM (2 occurrences)
Last logged: 6:38:41 PM

Error while setting up petsafe platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/petsafe/button.py", line 33, in async_setup_entry
    ButtonEntities.PetSafeLitterboxButtonEntity(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass=hass,
        ^^^^^^^^^^
    ...<3 lines>...
        coordinator=coordinator,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/petsafe/ButtonEntities.py", line 63, in __init__
    sw_version=device.firmware,
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/petsafe/devices.py", line 454, in firmware
    return self.data["shadow"]["state"]["reported"]["firmware"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'firmware'
``` 

I have the 1.3.5 Installed and the HA is 2024.12.3

**Comment by danhajduk** [comment]
I have downgraded to 1.3.0 and now it works

**Comment by nsheldon** [comment]
I'm experiencing this as well with the PetSafe ScoopFree smart litter box.  The PetSafe integration successfully logs into my PetSafe account but does not add the device or any entities.  Errors below.

Using Home Assistant OS 14.2 with Core 2025.1.4.

`Logger: homeassistant.components.button
Source: helpers/entity_platform.py:366
integration: Button (documentation, issues)
First occurred: 10:37:22 PM (4 occurrences)
Last logged: 11:28:04 PM

Error while setting up petsafe platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/petsafe/button.py", line 33, in async_setup_entry
    ButtonEntities.PetSafeLitterboxButtonEntity(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass=hass,
        ^^^^^^^^^^
    ...<3 lines>...
        coordinator=coordinator,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/petsafe/ButtonEntities.py", line 63, in __init__
    sw_version=device.firmware,
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/petsafe/devices.py", line 454, in firmware
    return self.data["shadow"]["state"]["reported"]["firmware"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'firmware'
`

**Comment by nsheldon** [comment]
I updated to Core 2025.2.1 and still see errors in the log with no devices or entities loaded from PetSafe.

EDIT: I should note that the "Litter Box Details" section of the PetSafe app for this litter box shows absolutely nothing for the "Firmware Version".  This is a brand new litter box so maybe they don't include that detail in the litter box info any longer?

`Logger: homeassistant.components.button
Source: helpers/entity_platform.py:366
integration: Button (documentation, issues)
First occurred: 11:47:50 PM (1 occurrences)
Last logged: 11:47:50 PM

Error while setting up petsafe platform for button: 'firmware'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/petsafe/button.py", line 33, in async_setup_entry
    ButtonEntities.PetSafeLitterboxButtonEntity(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass=hass,
        ^^^^^^^^^^
    ...<3 lines>...
        coordinator=coordinator,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/petsafe/ButtonEntities.py", line 63, in __init__
    sw_version=device.firmware,
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/petsafe/devices.py", line 454, in firmware
    return self.data["shadow"]["state"]["reported"]["firmware"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'firmware'
`
